# Generated by Django 4.0.2 on 2022-02-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='productlist',
            name='quantity',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
