# Generated by Django 4.0.2 on 2022-04-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_services', '0002_alter_category_options_productlist_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtelProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
    ]
