# Generated by Django 4.0.2 on 2022-04-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_services', '0004_alter_airtelproductlist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Datashare Categories'},
        ),
    ]
