# Generated by Django 4.0.2 on 2022-02-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtime_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
