# Generated by Django 4.0.2 on 2022-02-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtime_services', '0002_transaction_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
