# Generated by Django 4.0.2 on 2022-04-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airtime_services', '0003_transaction_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
