# Generated by Django 4.0.2 on 2022-03-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_paymentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=255)),
            ],
        ),
    ]
