# Generated by Django 4.0.2 on 2022-04-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_paymentnotification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_wallet_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_balance', models.CharField(max_length=255)),
            ],
        ),
    ]
