# Generated by Django 4.0.2 on 2022-02-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='funding_account_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='funding_bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
