# Generated by Django 4.0.2 on 2022-02-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_funding_account_no_profile_funding_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
