# Generated by Django 4.0.2 on 2022-04-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education Product List'},
        ),
    ]
